pub const GUILDS:i32 =  (1 << 0);
// - GUILD_CREATE
// - GUILD_UPDATE
// - GUILD_DELETE
// - GUILD_ROLE_CREATE
// - GUILD_ROLE_UPDATE
// - GUILD_ROLE_DELETE
// - CHANNEL_CREATE
// - CHANNEL_UPDATE
// - CHANNEL_DELETE
// - CHANNEL_PINS_UPDATE
// - THREAD_CREATE
// - THREAD_UPDATE
// - THREAD_DELETE
// - THREAD_LIST_SYNC
// - THREAD_MEMBER_UPDATE
// - THREAD_MEMBERS_UPDATE *
// - STAGE_INSTANCE_CREATE
// - STAGE_INSTANCE_UPDATE
// - STAGE_INSTANCE_DELETE

pub const GUILD_MEMBERS: i32 = (1 << 1);
// - GUILD_MEMBER_ADD
// - GUILD_MEMBER_UPDATE
// - GUILD_MEMBER_REMOVE
// - THREAD_MEMBERS_UPDATE *

pub const GUILD_MODERATION: i32 = (1 << 2);
// - GUILD_AUDIT_LOG_ENTRY_CREATE
// - GUILD_BAN_ADD
// - GUILD_BAN_REMOVE

pub const GUILD_EMOJIS_AND_STICKERS: i32 = (1 << 3);
// - GUILD_EMOJIS_UPDATE
// - GUILD_STICKERS_UPDATE

pub const GUILD_INTEGRATIONS: i32 = (1 << 4);
// - GUILD_INTEGRATIONS_UPDATE
// - INTEGRATION_CREATE
// - INTEGRATION_UPDATE
// - INTEGRATION_DELETE

pub const GUILD_WEBHOOKS: i32 = (1 << 5);
// - WEBHOOKS_UPDATE

pub const GUILD_INVITES: i32 = (1 << 6);
// - INVITE_CREATE
// - INVITE_DELETE

pub const GUILD_VOICE_STATES: i32 = (1 << 7);
// - VOICE_STATE_UPDATE

pub const GUILD_PRESENCES: i32 = (1 << 8);
// - PRESENCE_UPDATE

pub const GUILD_MESSAGES: i32 = (1 << 9);
// - MESSAGE_CREATE
// - MESSAGE_UPDATE
// - MESSAGE_DELETE
// - MESSAGE_DELETE_BULK

pub const GUILD_MESSAGE_REACTIONS: i32 = (1 << 10);
// - MESSAGE_REACTION_ADD
// - MESSAGE_REACTION_REMOVE
// - MESSAGE_REACTION_REMOVE_ALL
// - MESSAGE_REACTION_REMOVE_EMOJI

pub const GUILD_MESSAGE_TYPING: i32 = (1 << 11);
// - TYPING_START

pub const DIRECT_MESSAGES: i32 = (1 << 12);
// - MESSAGE_CREATE
// - MESSAGE_UPDATE
// - MESSAGE_DELETE
// - CHANNEL_PINS_UPDATE

pub const DIRECT_MESSAGE_REACTIONS: i32 = (1 << 13);
// - MESSAGE_REACTION_ADD
// - MESSAGE_REACTION_REMOVE
// - MESSAGE_REACTION_REMOVE_ALL
// - MESSAGE_REACTION_REMOVE_EMOJI

pub const DIRECT_MESSAGE_TYPING: i32 = (1 << 14);
// - TYPING_START

pub const MESSAGE_CONTENT: i32 = (1 << 15) ;

pub const GUILD_SCHEDULED_EVENTS: i32 = (1 << 16);
// - GUILD_SCHEDULED_EVENT_CREATE
// - GUILD_SCHEDULED_EVENT_UPDATE
// - GUILD_SCHEDULED_EVENT_DELETE
// - GUILD_SCHEDULED_EVENT_USER_ADD
// - GUILD_SCHEDULED_EVENT_USER_REMOVE

pub const AUTO_MODERATION_CONFIGURATION: i32 = (1 << 20);
// - AUTO_MODERATION_RULE_CREATE
// - AUTO_MODERATION_RULE_UPDATE
// - AUTO_MODERATION_RULE_DELETE

pub const AUTO_MODERATION_EXECUTION: i32 = (1 << 21);
// - AUTO_MODERATION_ACTION_EXECUTION

pub const GUILD_MESSAGE_POLLS: i32 = (1 << 24);
// - MESSAGE_POLL_VOTE_ADD
// - MESSAGE_POLL_VOTE_REMOVE

pub const DIRECT_MESSAGE_POLLS: i32 = (1 << 25);
// - MESSAGE_POLL_VOTE_ADD
// - MESSAGE_POLL_VOTE_REMOVE