import { HorizontalBox, ScrollView, Button, VerticalBox, TextEdit } from "std-widgets.slint";

struct User {
	name: string,
}
struct Guild {
	pfp_path: string,
}

export component Chat {
	property <[User]> users;
	// property <[Guild]> guilds;
	property <[Guild]> guilds: [
		{pfp_path: "test"},
		{pfp_path: "test"},
		{pfp_path: "test"},
		{pfp_path: "test"},
	];

    HorizontalBox {
		VerticalBox {
			width: 64px;

			Button {
				text: "DMs";
			}
			ScrollView {
				viewport-height: guilds.length * 64px;
				for guild[i] in guilds: Button {
					y: i * 64px;
					text: guild.pfp_path;
				}
			}
		}
		VerticalBox { 
			Button {
				text: "Friends";
			}
			ScrollView {
				viewport-height: guilds.length * 64px;
				for user[i] in users: Button {
					y: i * 64px;
					text: user.name;
				}
			} 
		}
		VerticalBox { 
			Text { text: "User"; }
			TextEdit { }
		}
		
    }
}
