import { HorizontalBox, ScrollView, Button, VerticalBox, TextEdit } from "std-widgets.slint";

struct Conversation {
	// MetaData
	platform: string,
	id: string,
	
	// Data
	name: string,
	image: image,
}
struct Guild {
	pfp_path: string,
}

export global ChatGlobal {
	in property <[Conversation]> conversations;
	callback set_selected_conversation(Conversation);
}

export component Chat {
	property <[Guild]> guilds: [
		{pfp_path: "test"},
		{pfp_path: "test"},
		{pfp_path: "test"},
		{pfp_path: "test"},
	];

    HorizontalBox {
	// GUILDS
		VerticalBox {
			width: 64px;

			Button {
				text: "DMs";
			}
			ScrollView {
				viewport-height: guilds.length * 64px;
				for guild[i] in guilds: Button {
					y: i * 64px;
					icon: @image-url("../public/Assets/avatar.png");
				}
			}
		}
		// SIDE BAR
		VerticalBox { 
			Button {
				text: "Friends";
			}
			ScrollView {
				viewport-height: guilds.length * 64px;
				for conversation[i] in ChatGlobal.conversations: Button {
					icon: conversation.image;
					y: i * 64px;
					text: conversation.name;
					clicked => { ChatGlobal.set_selected_conversation(conversation) }
				}
			} 
		}
		// CHAT
		VerticalBox { 
			Text { text: "User"; }
			TextEdit { }
		}
		
    }
}
